In [ ]:
#getting a sample code of printing age
a=10
print("I am ",a," years old")

I am  10  years old


In [ ]:
#addition of two numbers
a=int(input("Enter a number: "))
b=int(input("Enter another number: "))
c=a+b;
print("Addition is ",c)
print("subtraction is ",a-b)
print("Product is ",a*b)
print("Division is ",a/b)
print("Remainder is ",a%b)
print("Power of a to the b is ",a**b)
print("Floor division is ",a//b)

Enter a number: 87
Enter another number: 89
Addition is  176
subtraction is  -2
Product is  7743
Division is  0.9775280898876404
Remainder is  87
Power of a to the b is  41420323172887136317090775242992936475770796498047502858229021582473014613526597928360296793410319531028123733525957305462754476185238404911054531704443764438196755277867927
Floor division is  0


In [ ]:
#take salary from the user if the salary is more than 50000 there is a 10% tax print his final salary
sal=int(input("Enter your salary: "))
if(sal>=50000):
  n=sal-(10*sal)/100
  print("The user salary is ",n)
else:
  print("There is no tax for the user.Salary=",sal)

Enter your salary: 15000
There is no tax for the user.Salary= 15000


In [ ]:
#get the salary from the user if the salary is more than or equal to 50k apply 10% tax deduction if the salary is lessthan 50k apply 5% tax if the salary is more than 70k apply 12% tax if salary exceeds 1lakh print you are promoted to next level

In [ ]:
a=int(input("Enter the salary of user: "))
if(a<50000):
  n=a-(5*a)/100
  print("The user salary is ",n)
elif(a<70000):
   n=a-(10*a)/100
   print("The user salary is ",n)
elif(a<100000):
  n=a-(12*a)/100
  print("The salary is ",n)
else:
  print("You are promoted...")

Enter the salary of user: 75000
The salary is  66000.0


In [ ]:
n=int(input("Enter a number: "))
for i in range(1,11,1):
  p=n*i
  print(n,"*",i,"=",p)


Enter a number: 15
15 * 1 = 15
15 * 2 = 30
15 * 3 = 45
15 * 4 = 60
15 * 5 = 75
15 * 6 = 90
15 * 7 = 105
15 * 8 = 120
15 * 9 = 135
15 * 10 = 150


In [ ]:
n=int(input("Enter a number: "))
i=1
while(i<=10):
  p=n*i
  print(n,"*",i,"=",p)
  i+=1

Enter a number: 15
15 * 1 = 15
15 * 2 = 30
15 * 3 = 45
15 * 4 = 60
15 * 5 = 75
15 * 6 = 90
15 * 7 = 105
15 * 8 = 120
15 * 9 = 135
15 * 10 = 150


In [ ]:
#create a heterogeneous list
l1=[1,31,50.11,'string']
print(l1)
for i in l1:
  print(i)
l1.append("string2")#adds element at back of the list
print(l1)
l1.insert(2,'8999')
print(l1)


[1, 31, 50.11, 'string']
1
31
50.11
string
[1, 31, 50.11, 'string', 'string2']
[1, 31, '8999', 50.11, 'string', 'string2']


In [ ]:
l2=['hello','world']
l1.extend(l2)#l1+l2
print(l3)

[1, 31, '8999', 50.11, 'string', 'string2', 'hello', 'world']


In [ ]:
l1.remove('8999')#removes the element
l1.pop(5)#removes the index element
print(l1)

[50.11, 'string', 'hello', 'world', 'hello']


In [ ]:
l1.clear()#clears the data in the list
print(l1)

[]


In [ ]:
#create a list of random integers i need 10 elements print their squares save this squares in a new list
l1=[12,9,8,7,4,44,54,21,99,100]
l2=[]
for i in l1:
  l2.append(i*i)
print(l2)

[144, 81, 64, 49, 16, 1936, 2916, 441, 9801, 10000]


In [ ]:
#using list comprehension
l1=[12,9,8,7,4,44,54,21,99,100]
l2=[i*i for i in l1]
print(l2)

[144, 81, 64, 49, 16, 1936, 2916, 441, 9801, 10000]


In [ ]:
#create a list of random integers print their squares save this squares in a new list if the elements in list is >50
l1=[22,33,44,55,66,77,88]
l2=[]
for i in l1:
  if(i>50):
    l2.append(i * i)
print(l2)

[3025, 4356, 5929, 7744]


In [1]:
l1=[11,22,33,44,55,66,77,88]
l2=[i*i if (i>50) else 'x' for i in l1]
print(l2)

['x', 'x', 'x', 'x', 3025, 4356, 5929, 7744]


In [8]:
#take the salary from the user if the salary is <<50k 10% tax otherwise 15% tax
l1=[250000,120000,30000,55000]
l2=[n-(n*10/100) if(n<50000) else n-(n*15/100) for n in l1]
print(l2)

[212500.0, 102000.0, 27000.0, 46750.0]


In [ ]:
#dictionary syntax:
#   d={key1:value1,key2:value2,key3:value3}

In [19]:
d1={'word':'Hello','number':5000,'letter':'l','word':'World'}
print(d1['word'])

World


In [28]:
dict1={'dept':'cse','details':{'year':2,'sec':'d','count':72}}
print("Year is",dict1['details']['year'])
print("section is",dict1['details']['sec'])
print("count is",dict1['details']['count'])

Year is 2
section is d
count is 72


In [42]:
l1=[1,2,3,4,5]
l2=['rajamouli','neel','shankar','lokesh','upendra']
newzip=zip(l1,l2)
result_list =list(newzip)
print(result_list)

[(1, 'rajamouli'), (2, 'neel'), (3, 'shankar'), (4, 'lokesh'), (5, 'upendra')]


In [44]:
#numpy
import numpy as np
A = np.array([1,2,3,4]) #1d array
print(A.ndim)
print(A.shape)

1
(4,)


In [49]:
import numpy as np
a2=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])     #2d array
#element in each row is equal to each coloumn
print(a2.ndim)
print(a2.shape)
print(a2)

2
(3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [51]:
a3=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
print(a3.ndim)      #3d array
print(a3.shape)
print(a3)


3
(2, 3, 3)
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [58]:
a=np.ones((2,5,4))    #groups,rows,coloumns
print(a)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [57]:
a=np.zeros((2,5,4))    #groups,rows,coloumns
print(a)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [59]:
a=np.eye(4)     #identity matrix using numpy
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [61]:
a=np.arange(1,10,2)     #start,stop,step
print(a)

[1 3 5 7 9]


In [62]:
#print all the numbers that are divisible by 8 using arange function b/w 1 & 1000
a=np.arange(8,1001,8)
print(a)

[   8   16   24   32   40   48   56   64   72   80   88   96  104  112
  120  128  136  144  152  160  168  176  184  192  200  208  216  224
  232  240  248  256  264  272  280  288  296  304  312  320  328  336
  344  352  360  368  376  384  392  400  408  416  424  432  440  448
  456  464  472  480  488  496  504  512  520  528  536  544  552  560
  568  576  584  592  600  608  616  624  632  640  648  656  664  672
  680  688  696  704  712  720  728  736  744  752  760  768  776  784
  792  800  808  816  824  832  840  848  856  864  872  880  888  896
  904  912  920  928  936  944  952  960  968  976  984  992 1000]


In [65]:
#splitting a range of numbers into n numbers with common differences
a=np.linspace(48,59,10)
print(a)

[48.         49.22222222 50.44444444 51.66666667 52.88888889 54.11111111
 55.33333333 56.55555556 57.77777778 59.        ]


In [ ]:
#study tuples & sets
#documentation