In [ ]:
#reshape
import numpy as np
A=np.arange(1,13).reshape(3,4)
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


#resize ->>> changes the shape of original array
#reshape ->>> changes needs to save in another variable

In [ ]:
a=np.linspace(48,59,8).reshape(4,2)
print(a)

[[48.         49.57142857]
 [51.14285714 52.71428571]
 [54.28571429 55.85714286]
 [57.42857143 59.        ]]


In [ ]:
b=np.array([11,22,51,63,89,19,25,18,35]).reshape(3,3)
print(b)

[[11 22 51]
 [63 89 19]
 [25 18 35]]


In [ ]:
#resize
b=np.array([11,22,51,63,89,19,25,18,35])
b.resize(2,2,2)
print(b)

[[[11 22]
  [51 63]]

 [[89 19]
  [25 18]]]


In [ ]:
#subtracting array elements
a=np.array([1,15,13,23])
b=np.array([11,55,67,64])
c=b-a
print(c)

[10 40 54 41]


In [ ]:
#adding array elements
a=np.array([1,15,13,23])
b=np.array([11,55,67,64])
c=b+a
print(c)

[12 70 80 87]


In [ ]:
a=np.array([1,15,13,23]).reshape(2,2)
b=np.array([11,55,67,64]).reshape(2,2)
print(a)
print("__________")
print(b)
print("__________")
c=a*b         #one on one multiplication
print(c)

[[ 1 15]
 [13 23]]
__________
[[11 55]
 [67 64]]
__________
[[  11  825]
 [ 871 1472]]


In [ ]:
a=np.array([1,15,13,23]).reshape(2,2)
b=np.array([11,55,67,64]).reshape(2,2)
print(a)
print("__________")
print(b)
print("__________")
c=a@b         #matrix multiplication
print(c)

[[ 1 15]
 [13 23]]
__________
[[11 55]
 [67 64]]
__________
[[1016 1015]
 [1684 2187]]


In [ ]:
a=np.array([1,15,13,23]).reshape(2,2)
b=np.array([11,55,67,64]).reshape(2,2)
print(a)
print("__________")
print(b)
print("__________")
c=a.dot(b)         #matrix multiplication
print(c)

[[ 1 15]
 [13 23]]
__________
[[11 55]
 [67 64]]
__________
[[1016 1015]
 [1684 2187]]


In [ ]:
a=np.array([1,15,13,23,99,21,52])
print(a.max())    #maximum value
print(a.min())     #minimum value
#max and min will work to intergers,float values

99
1


In [ ]:
a=np.array([1.91,15.6,13.1,23.5,99.8,21.2,52.11])
print(a.max())    #maximum value
print(a.min())     #minimum value

99.8
1.91


In [ ]:
a=np.array([1,15,13,23]).reshape(2,2)
b=np.array([11,55,67,64]).reshape(2,2)
print(a)
print(a.max(axis=0))      #axis = 0 = coloumns
print(a.max(axis=1))      #axis = 1 = rows

[[ 1 15]
 [13 23]]
[13 23]
[15 23]


In [ ]:
a=np.array([1,15,13,23]).reshape(2,2)
b=np.array([11,55,67,64]).reshape(2,2)
print(a)
print(a.min(axis=0))      #axis = 0 = coloumns
print(a.min(axis=1))      #axis = 1 = rows

[[ 1 15]
 [13 23]]
[ 1 15]
[ 1 13]


In [ ]:
a=np.array([15,11,14,10,77,34,45,56,67]).reshape(3,3)
print(a.max(axis=1))
print(a)

[15 77 67]
[[15 11 14]
 [10 77 34]
 [45 56 67]]


In [ ]:
#joining arrays
a=np.array([1,15,13,23]).reshape(2,2)
b=np.array([11,55,67,64]).reshape(2,2)
print(a)
print(b)
print("After vertical stack:")
print(np.vstack((a,b)))

[[ 1 15]
 [13 23]]
[[11 55]
 [67 64]]
After vertical stack:
[[ 1 15]
 [13 23]
 [11 55]
 [67 64]]


In [ ]:
#joining arrays
a=np.array([1,15,13,23]).reshape(2,2)
b=np.array([11,55,67,64]).reshape(2,2)
print(a)
print(b)
print("After horizontal stack:")
print(np.hstack((a,b),))

[[ 1 15]
 [13 23]]
[[11 55]
 [67 64]]
After horizontal stack:
[[ 1 15 11 55]
 [13 23 67 64]]


In [ ]:
#joining arrays
a=np.array([1,15,13,23]).reshape(2,2)
b=np.array([11,55,67,64]).reshape(2,2)
print(a)
print(b)
print("After horizontal stack:")
print(np.stack((a,b),axis=1))

[[ 1 15]
 [13 23]]
[[11 55]
 [67 64]]
After horizontal stack:
[[[ 1 15]
  [11 55]]

 [[13 23]
  [67 64]]]


In [ ]:
a=np.arange(30).reshape(2,3,5)
print(a)
print("After dstack")
print(np.dstack(a))
#dstack is used for groups
#no.of rows --> no.of groups
#no.of col in every group --> no.of rows in every group

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
After dstack
[[[ 0 15]
  [ 1 16]
  [ 2 17]
  [ 3 18]
  [ 4 19]]

 [[ 5 20]
  [ 6 21]
  [ 7 22]
  [ 8 23]
  [ 9 24]]

 [[10 25]
  [11 26]
  [12 27]
  [13 28]
  [14 29]]]


In [ ]:
#splitting arrays
a=np.arange(18).reshape(6,3)
print(a)
print("After splitting: ")
print(np.vsplit(a,(2,3)))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
After splitting: 
[array([[0, 1, 2],
       [3, 4, 5]]), array([[6, 7, 8]]), array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])]


In [ ]:
#splitting arrays
a=np.arange(18).reshape(6,3)
print(a)
print("After splitting: ")
print(np.hsplit(a,3))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
After splitting: 
[array([[ 0],
       [ 3],
       [ 6],
       [ 9],
       [12],
       [15]]), array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]])]


In [ ]:
#splitting arrays
a=np.arange(18).reshape(3,6)
print(a)
print("After splitting: ")
print(np.hsplit(a,(2,3)))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
After splitting: 
[array([[ 0,  1],
       [ 6,  7],
       [12, 13]]), array([[ 2],
       [ 8],
       [14]]), array([[ 3,  4,  5],
       [ 9, 10, 11],
       [15, 16, 17]])]


In [ ]:
a=np.array([11,52,62,521,876,5])
print(a.argmax())     #argmax returns the maximum element position of the array

4


In [ ]:
a=np.array([11,52,62,521,876,5])
print(a.argmin())     #argmin returns the minimum element position of the array

5


In [ ]:
a=np.array([11,52,62,521,876,5]).reshape(2,3)
print(a)
print(a.argmax(axis=0))       #argmax using axis
print(a.argmax(axis=1))       #argmin using axis

[[ 11  52  62]
 [521 876   5]]
[1 1 0]
[2 1]


In [ ]:
a=np.array([11,52,62,521,876,5]).reshape(2,3)
print(a)
print(a.argmin(axis=0))       #argmin using axis
print(a.argmin(axis=1))       #argmin using axis

[[ 11  52  62]
 [521 876   5]]
[0 0 1]
[0 2]


In [ ]:
#statistics ->>> mean,median,std,var
a=np.array([11,52,62,521,876,5])
print(np.mean(a))           #mean
print(np.median(a))         #median
print(np.std(a))            #standard deviation
print(np.var(a))            #variance

254.5
57.0
330.88001349935496
109481.58333333333


In [ ]:
#trigonometry
a=np.pi
print(a)      #radians
np.rad2deg(a)   #converts radians to degrees

3.141592653589793


180.0

In [ ]:
degrees array

[0.78539816 1.04719755 1.57079633 3.14159265]
[ 45.  60.  90. 180.]


In [ ]:
c=np.array([0,30,45,60,90,120,180])
print(np.deg2rad(c))      #converts degrees to radians

[0.         0.52359878 0.78539816 1.04719755 1.57079633 2.0943951
 3.14159265]


In [ ]:
print(np.sin(c))
print(np.cos(c))
print(np.tan(c))

[ 0.         -0.98803162  0.85090352 -0.30481062  0.89399666  0.58061118
 -0.80115264]
[ 1.          0.15425145  0.52532199 -0.95241298 -0.44807362  0.81418097
 -0.59846007]
[ 0.         -6.4053312   1.61977519  0.32004039 -1.99520041  0.71312301
  1.33869021]


In [ ]:
np.arccos(1)      #cos^-1

0.0

In [ ]:
np.arcsin(1)      #sin^-1

1.5707963267948966

In [ ]:
np.arctan(1)      #tan^-1

0.7853981633974483

In [ ]:
a=np.array([33,61,45,81,94,19,75])
print(np.searchsorted(a,33))          #output the index of a sorted element

0


In [ ]:
a=np.array([33,61,45,81,94,19,75])
b=np.array([11,22,33,44,55,66,77])
print(np.add(a,b))            #adding two arrays
print(np.subtract(a,b))       #subtracting two arrays
print(np.divide(a,b))         #divide two arrays
print(np.mod(a,b))            #remainder of two arrays
print(np.divmod(a,b))         #gets the remainder and quotient as well

[ 44  83  78 125 149  85 152]
[ 22  39  12  37  39 -47  -2]
[3.         2.77272727 1.36363636 1.84090909 1.70909091 0.28787879
 0.97402597]
[ 0 17 12 37 39 19 75]
(array([3, 2, 1, 1, 1, 0, 0]), array([ 0, 17, 12, 37, 39, 19, 75]))


In [3]:
a=np.array([33,61,45,81,94,19,75])
b=(np.sort(a))
print(b)

[19 33 45 61 75 81 94]


In [4]:
import numpy as np
np.diff(b)

array([14, 12, 16, 14,  6, 13])

In [ ]:
a=np.array([33,61,45,81,94,19,75])
b=np.array([11,22,33,44,55,66,77])
print(np.intersect1d(a,b))

[33]


In [ ]:
a=np.array([33,61,45,81,94,19,75])
b=np.array([11,22,33,44,55,66,77])
print(np.union1d(a,b))

[11 19 22 33 44 45 55 61 66 75 77 81 94]


In [ ]:
a=np.array([61,45,81,94,19,75])
b=np.array([11,22,44,55,66,77])
print(np.setdiff1d(a,b))

[19 45 61 75 81 94]


In [ ]:
#rounding
#trunc
a=np.trunc(3.11)
print(a)
#ceil
a=np.ceil([3.1479,-3.1084])
print(a)
#floor
a=np.floor([-4.11,7.1245])
print(a)
#around
a=np.around(3.123456,4)
print(a)
#fix
a=np.fix([3.14,-2.421])
print(a)

3.0
[ 4. -3.]
[-5.  7.]
3.1235
[ 3. -2.]


more functions
:cumulative sum
:reduce


In [ ]:
a=np.array([3,4,16,19,10])
print(np.cumsum(a))

[ 3  7 23 42 52]


In [ ]:
a=np.array([3,4,16,19,10])
print(np.cumprod(a))

[    3    12   192  3648 36480]


In [ ]:
a=np.lcm(121,525)
b=np.gcd(121,525)
print(a)
print(b)

63525
1


In [ ]:
a=np.array([45,30,15,60,10])
print(np.lcm.reduce(a))
print(np.gcd.reduce(a))

180
5


In [ ]:
#inverse matrix
#linear inverse
a=np.array([[1,2],[3,4]])
print(np.linalg.inv(a))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
#to import subfunctions in numpy
from numpy import random as rd

In [ ]:
#rand and randint
#rand
a=rd.rand()
print(a)
b=rd.rand(10)
print(b)

0.9649225983173827
[0.19881241 0.46689977 0.96340466 0.32658683 0.16953754 0.72473062
 0.99842486 0.9728522  0.00524004 0.1040224 ]


In [ ]:
#randint
a=rd.randint(5)
print(a)

1


In [ ]:
a=rd.randint(50,size=(2,3))
print(a)

[[ 7 43 45]
 [29 48 37]]


In [ ]:
#inner outer and cross
a=np.array([1,2,3])
b=np.array([12,41,63])
#inner==(1*12)+(2*41)+(3*63)
print(np.inner(a,b))

283


In [ ]:
a=np.array([1,2,3])
b=np.array([12,41,63])
#outer==(1st row =1st row 1st element * 2nd row)(2nd row = 2nd row *1st row 2nd element)
print(np.outer(a,b))

[[ 12  41  63]
 [ 24  82 126]
 [ 36 123 189]]


In [ ]:
a=np.array([1,2,3])
b=np.array([12,41,63])
#cross=det
print(np.cross(a,b))

[  3 -27  17]
